set_property PACKAGE_PIN W4 [get_ports {control[3]}]
set_property PACKAGE_PIN V4 [get_ports {control[2]}]
set_property PACKAGE_PIN U4 [get_ports {control[1]}]
set_property PACKAGE_PIN U2 [get_ports {control[0]}]
set_property PACKAGE_PIN W7 [get_ports {dis[6]}]
set_property PACKAGE_PIN W6 [get_ports {dis[5]}]
set_property PACKAGE_PIN U8 [get_ports {dis[4]}]
set_property PACKAGE_PIN V8 [get_ports {dis[3]}]
set_property PACKAGE_PIN U5 [get_ports {dis[2]}]
set_property PACKAGE_PIN V5 [get_ports {dis[1]}]
set_property PACKAGE_PIN U7 [get_ports {dis[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dis[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property PACKAGE_PIN W19 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
